version: "3.8"

services:
  web:
    build: ./myairbnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myairbnb_backend/:/usr/src/myairbnb_backend/
    ports:
      - 8000:8000
    env_file:
      - ./myairbnb_backend/.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=myairbnb

volumes:
  postgres_data:
